### ISSUE TITLE
Setup metrics scraping for all apps

### ISSUE THREAD

**Issue by lorenzo-w** [lorenzo-w/k3sx#37]
- [ ] ingress-nginx:

```yaml
controller.metrics.enabled: true
controller.metrics.serviceMonitor.enabled: true
```

- [ ] cert-manager:

```yaml
prometheus.enabled: true
prometheus.servicemonitor.enabled: true
```

- [ ] cilium (hubble):

```yaml
hubble.metrics.enabled: true
hubble.metrics.serviceMonitor.enabled: true
```

- [ ] external-dns:

```yaml
serviceMonitor.enabled: true
```

- [ ] longhorn:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: longhorn-prometheus-servicemonitor
  namespace: monitoring
  labels:
    name: longhorn-prometheus-servicemonitor
spec:
  selector:
    matchLabels:
      app: longhorn-manager
  namespaceSelector:
    matchNames:
    - longhorn-system
  endpoints:
  - port: manager
```
